{
 "title": "SE Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "количество обработанных ботом страниц",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    { "expr": "crawler_pages_parsed", "legendFormat": "Число страниц" }
   ]
  },
  {
   "title": "время затраченное ботом на подключение к веб-сайту и загрузку веб-страницы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "crawler_site_connection_time_sum",
     "legendFormat": "time sum"
    }
   ]
  },
  {
   "title": "время генерации веб-страниц",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "targets": [
    { "expr": "web_page_gen_time_sum", "legendFormat": "время генерации" }
   ]
  },
  {
   "title": " количество обработанных запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "targets": [
    { "expr": "web_pages_served", "legendFormat": "кол-во запросов" }
   ]
  },
  {
   "title": "время затраченное ботом на обработку содержимого веб-страницы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "crawler_page_parse_time_sum",
     "legendFormat": "время затраченное ботом на обработку"
    }
   ]
  },
  {
   "title": "Crawler",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"search-engine\", component=\"crawler\"} |= ``"
    }
   ]
  },
  {
   "title": "UI",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"search-engine\", component=\"ui\"} |= ``"
    }
   ]
  }
 ]
}