kube-prometheus-stack: 
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
      - job_name: 'searchengine-crawler'
        metrics_path: /metrics
        static_configs:
        - targets: ['searchengine-crawler.app:8000']
      - job_name: 'searchengine-ui'
        metrics_path: /metrics
        static_configs:
        - targets: ['searchengine-ui.app:8000']

  alertmanager:
    config:
      global:
        resolve_timeout: 5m
        telegram_api_url: 'https://api.telegram.org'
      route:
        group_by: ['alertname', 'cluster', 'service']
        group_wait: 30s
        group_interval: 30s
        repeat_interval: 3h
        receiver: 'default-receiver'
        routes:
        - match:
            alertname: DeadMansSwitch
          receiver: 'null'
      inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'cluster', 'service']
      receivers:
      - name: 'default-receiver'
        telegram_configs:
        - bot_token: ''
          api_url: 'https://api.telegram.org'
          chat_id: 53694183
          parse_mode: 'HTML'
          message: |
            {{ range .Alerts }}
              {{- if .Annotations.summary }}*Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`{{- end }}
              *Description:* {{ .Annotations.description }}{{ .Annotations.message }}
              *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
            {{ end }}
      - name: 'null'

  grafana:
    sidecar:
      datasources:
        defaultDatasourceEnabled: true
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://{{ .Release.Name }}-loki-gateway

promtail:
  config:
    clients:
      - url: http://{{ .Release.Name }}-loki-gateway/loki/api/v1/push
        tenant_id: 1
